import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const DynamicScores = dynamic(() => import("./components/header"), {
  loading: () => <p className="text-center">Kraunama...</p>,
  ssr: false,
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicScores />

        {children}
      </body>
    </html>
  );
}
